<h2>Login Page</h2>

<form method="POST">

    <div>
        <label for="username">Username </label>
        <input type="text" name="username" id="username" required>
    </div>
    
    <div>
        <label for="password">Password </label>
        <input type="password" name="password" id="password" required>
    </div>
    
    <button name="loginForm">Login</button>

</form>


<p>Don't have an account? Register here <a href="./register.php">Register</a></p>