<div>
    <h2>Register page</h2>
</div>


<form method="POST">

    <div>
        <label for="username">Username </label>
        <input type="text" name="username" id="username" required>
    </div>

    <div>
        <label for="email">E-mail </label>
        <input type="email" name="email" id="email" required>
    </div>

    <div>
        <label for="password">Password </label>
        <input type="password" name="password" id="password" required>
    </div>

    <div>
        <label for="passwordAgain">Password again </label>
        <input type="password" name="passwordAgain" id="passwordAgain" required>
    </div>

    <button name="registerSubmit">Register</button>
    
</form>
