<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>

        td {
            max-width: 200px;
            height: 30px;
            padding: 0px 10px;
            border: solid black;

        }

        table {
            overflow: hidden;
            border-collapse: collapse;
        }



    </style>
</head>
<body>
    <header>        
        <nav>
            <ul>
                <li>
                    <a href="/Webproject/index.php">Home</a>
                </li>
                <li>
                    <a href="/Webproject/about_us.php">About us</a>
                </li>
                <li>
                    <a href="/Webproject/view_languages.php">List of languages</a>
                </li>

                <?php  // after this statement add if its admin and then manage users, manage languages
                        if($_SESSION["role"] !== ""){ ?>
                    <li>
                        <a href="/Webproject/add_language.php">Add a new laguage</a>
                    </li>   

                <?php if($_SESSION["role"] === "admin"){  ?>
                        
                        <li>
                            <a href="/Webproject/edit_language.php">Edit languages</a>
                        </li>   

                        <li>
                            <a href="/Webproject/edit_user.php">Edit users</a>
                        </li>   

                 <?php }  ?>
                    <li>
                        <p>You are logged as <?php echo $_SESSION["username"]?></p>
                    </li>
                    <li>
                    
                        <form method="POST">
                            <button name="logOutForm">Log out</button>
                        </form>
                    </li>   
                
                <?php } else { ?>

                    <li>
                        <a href="/Webproject/login.php">Login</a>
                    </li>

                <?php } 
                
                
                if(isset($_POST["logOutForm"])){
                        session_destroy();
                        header("Location: /Webproject/index.php");
                    }
                ?>
                </ul>
        </nav>
    </header>