<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pro Lang Hub</title>
    <style>
        td {
            max-width: 200px;
            height: 30px;
            padding: 0px 10px;
            border: solid black;

        }

        table {
            overflow: hidden;
            border-collapse: collapse;
        }

        body {
            background-color: #202020;
            color: white;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            margin: 0;
        }

        a {
            color: #007bff;
            border: solid black 2px;
            border-radius: 5px;
            display: inline-block;
            padding: 10px 20px;
            text-decoration: none;
        }

        a:hover {
            background-color: navy;
            color: white;
        }

        nav {
            justify-content: space-between;
            display: flex;
            margin: 40px;
        }

        footer {
            margin-top: auto;
            text-align: center;
            padding: 10px;
            background-color: #111;
            color: white;
        }

        .profile {

            display: flex;
            align-items: center;
            gap: 10px;
        }

        .centered-text {

            display: flex;
            justify-content: center;
            align-items: center;
            height: 300px;
            text-align: center;
            padding: 0 200px;
        }

        button {
            background: rgb(0, 28, 186);

            color: white;
        }

        button:hover {
            background: rgb(3, 41, 253);
            color: black;
        }

        .filters {
            display: flex;
            flex-direction: row;

        }

        .filters>* {
            padding: 10px;
        }


        .button-size {
            padding: 1px 10px;
        }

        .login {
            justify-content: center;
            display: inline-block;
            text-align: center;
        }

        .login>* {
            font-size: 20px;
        }

        .better-button {
            font-size: 15px;
            padding: 0 15px;
            margin: 10px
        }

        .form-group {
            margin: 5px;

        }
    </style>
</head>

<body>
    <header>
        <nav>

            <div>
                <a href="./index.php">Home</a>
            </div>
            <div>
                <a href="./about_us.php">About us</a>
            </div>
            <div>
                <a href="./view_languages.php">List of languages</a>
            </div>

            <?php
            if ($_SESSION["role"] !== "") { ?>
                <div>
                    <a href="./add_language.php">Add a new laguage</a>
                </div>

                <?php if ($_SESSION["role"] === "admin") {  ?>

                    <div>
                        <a href="./view_users.php">List of users</a>
                    </div>

                <?php }  ?>
                <div class="profile">
                    <p>You are logged as <?php echo $_SESSION["username"] ?></p>


                    <form method="POST">
                        <button name="logOutForm">Log out</button>
                    </form>
                </div>

            <?php } else { ?>

                <div>
                    <a href="./login.php">Login</a>
                </div>

            <?php }


            if (isset($_POST["logOutForm"])) {
                session_destroy();
                header("Location: ./index.php");
            }
            ?>

        </nav>
    </header>